-- AlterEnum: Add RECURSO to PecaType
ALTER TYPE "PecaType" ADD VALUE IF NOT EXISTS 'RECURSO';

-- AlterEnum: Add RECURSO-specific StyleSection values
ALTER TYPE "StyleSection" ADD VALUE IF NOT EXISTS 'REQUERIMENTO';
ALTER TYPE "StyleSection" ADD VALUE IF NOT EXISTS 'OBJETO';
ALTER TYPE "StyleSection" ADD VALUE IF NOT EXISTS 'IMPUGNACAO_FACTO';
ALTER TYPE "StyleSection" ADD VALUE IF NOT EXISTS 'DIREITO_RECURSO';
ALTER TYPE "StyleSection" ADD VALUE IF NOT EXISTS 'CONCLUSOES_RECURSO';
